# Goal
bool return_to_init
---
# Result
bool success
ExploreStatus status
string message
uint32 frontier_count_visited
---
# Feedback
ExploreStatus status
uint32 frontier_count_discovered
uint32 frontier_count_blacklisted
geometry_msgs/PoseStamped current_target
